name: test-job-summary

on:
  push:

jobs:
  test-job-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: ctest -V --test-dir build --output-junit build/test-results.xml
  
      - name: Parse Test Results
        run: python scripts/parse_results.py build/test-results.xml
